
services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        env_file:
        - .env
        volumes:
        - db:/var/lib/mysql
        ports:
        - "3306:3306"
        networks:
        - inception
        restart: always
        entrypoint: /etc/mysql/entrypoint.sh
        command: mariadbd --user=mysql
    nginx:
      container_name: nginx
      networks:
        - inception
      depends_on:
        - wordpress
      build:
        context: requirements/nginx
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - "443:443"
      restart: on-failure
      volumes:
        - web:/var/www/html
    wordpress:
      container_name: wordpress
      networks:
        - inception
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      depends_on:
        - mariadb
      env_file:
        - .env
      volumes:
        - web:/var/www/html
      restart: on-failure
      expose:
        - 9000
volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/flmuller/data/mariadb
  web:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/flmuller/data/wordpress
networks:
   inception:
     driver: bridge